/* ============================================
   Portfolio Terminal — Configuration
   Edit this file with your personal info.
   ============================================ */

const CONFIG = {
    name: 'Manuel',

    spotify: {
        // 1. Go to https://developer.spotify.com/dashboard
        // 2. Create an app (any name)
        // 3. Add your portfolio URL to "Redirect URIs" in app settings
        //    e.g. https://magana272.github.io/ or http://localhost:5500/
        // 4. Paste your Client ID below (safe to expose — PKCE uses no secret)
        clientId: 'e7991a811d4b410696b93dc1f8921571',
    },

    about: [
        '<span class="highlight">Manuel Magana</span>',
        '<span class="dim">─────────────────────────────────────────</span>',
        'Software Engineer with a background in neurobiology',
        'and bioinformatics, now building backend systems,',
        'distributed infrastructure, and developer tools.',
        '',
        '  <span class="secondary">&bull;</span> M.S. Computer Science @ Northeastern <span class="dim">(2026)</span>',
        '  <span class="secondary">&bull;</span> B.A. Neurobiology @ UC Berkeley <span class="dim">(2021)</span>',
        '  <span class="secondary">&bull;</span> Previously Bioinformatics Scientist @ Genentech',
        '  <span class="secondary">&bull;</span> Focused on scalable systems, data pipelines, and APIs',
        '',
        '  <span class="dim">github</span>    <a class="output-link" href="https://github.com/magana272" target="_blank" rel="noopener">github.com/magana272</a>',
        '  <span class="dim">linkedin</span>  <a class="output-link" href="https://linkedin.com/in/manuel-magana-359290160/" target="_blank" rel="noopener">linkedin.com/in/manuel-magana</a>',
        '  <span class="dim">email</span>     <a class="output-link" href="mailto:manuel.ramon.magana@gmail.com">manuel.ramon.magana@gmail.com</a>',
    ],

    experience: [
        '<span class="heading">─── Experience ─────────────────────────────</span>',
        '',
        '  <span class="highlight">&bull;</span> <span class="accent-cyan">Bioinformatics Scientist</span>',
        '    Genentech <span class="dim">&middot; Nov 2022 — Jul 2025 &middot; San Francisco, CA</span>',
        '',
        '    Designed a well-tested Python library integrated into',
        '    5 production pipelines, reducing manual review from',
        '    days to hours. Optimized PySpark ETL pipelines',
        '    processing 200GB+ mass spectrometry files &mdash;',
        '    partition tuning, broadcast joins, and Parquet caching',
        '    reduced batch runtime from hours to minutes.',
        '    Containerized pipelines with Docker for reproducible',
        '    execution across 3 research teams.',
        '',
        '  <span class="highlight">&bull;</span> <span class="accent-cyan">Research Technician</span>',
        '    Weill Cornell Medicine <span class="dim">&middot; Jan 2022 — Jul 2022 &middot; New York, NY</span>',
        '',
        '    Developed Python and Bash tooling for large-scale',
        '    biological sequence processing including FASTA parsing',
        '    and motif extraction. Managed reproducible research',
        '    workflows and multi-user compute environments.',
        '',
        '  <span class="highlight">&bull;</span> <span class="accent-cyan">Junior Data Scientist</span>',
        '    Endless West <span class="dim">&middot; Mar 2021 — Nov 2021 &middot; San Francisco, CA</span>',
        '',
        '    Built ML training pipelines for sensory attribute',
        '    prediction from chromatography data. Developed web',
        '    scrapers with BeautifulSoup to extract chemical',
        '    property data from public databases.',
    ],

    projects: [
        '<span class="heading">─── Projects ───────────────────────────────</span>',
        '',
        '  <span class="accent-cyan">&#9670; Physiological Signal Analytics Platform</span>',
        '    Two-layer analytics system: reusable Python ETL/analysis',
        '    library + production FastAPI REST service backed by DuckDB.',
        '    Low-latency endpoints for PCA, FFT, and spectral density.',
        '    <span class="dim">tech: Python, FastAPI, DuckDB, Pydantic</span>',
        '    <a class="output-link" href="https://github.com/magana272/popanedb-backend" target="_blank" rel="noopener">&rarr; API</a> &middot; <a class="output-link" href="https://github.com/magana272/POPANEpy" target="_blank" rel="noopener">&rarr; Library</a>',
        '',
        '  <span class="accent-cyan">&#9670; WhatToDo &mdash; AI Event Discovery Platform</span>',
        '    Dual-provider AI recommendation engine (Claude + GPT-4o)',
        '    with live web search. JWT auth, SQLAlchemy + AWS RDS,',
        '    deployed to App Runner via ECR with GitHub Actions CI/CD.',
        '    96% pytest coverage. Led backend for a 4-person team.',
        '    <span class="dim">tech: Python, FastAPI, Claude API, Docker, AWS</span>',
        '    <a class="output-link" href="https://bmjumiukye.us-east-1.awsapprunner.com/" target="_blank" rel="noopener">&rarr; Live</a>',
        '',
        '  <span class="accent-cyan">&#9670; Rate Limiter Service</span>',
        '    High-performance Go reverse proxy with fixed window and',
        '    token bucket rate limiting. Atomic Redis transactions',
        '    prevent race conditions under 1,000+ concurrent requests.',
        '    <span class="dim">tech: Go, Redis, Docker</span>',
        '    <a class="output-link" href="https://github.com/magana272/Rate-Limiter-Service" target="_blank" rel="noopener">&rarr; github.com/magana272/Rate-Limiter-Service</a>',
        '',
        '  <span class="accent-cyan">&#9670; Paxos Key-Value Store</span>',
        '    Fault-tolerant distributed KV store using Paxos consensus.',
        '    RPC-based node discovery, dynamic cluster joins, validated',
        '    under chaos testing with 10% acceptor failure rate.',
        '    <span class="dim">tech: Java, RPC</span>',
        '    <a class="output-link" href="https://github.com/magana272/PAXOS-Key-Value-Store" target="_blank" rel="noopener">&rarr; github.com/magana272/PAXOS-Key-Value-Store</a>',
    ],

    skills: [
        '<span class="heading">─── Skills ─────────────────────────────────</span>',
        '',
        '  <span class="secondary">Languages:</span>',
        '    Python  &middot;  Go  &middot;  Java  &middot;  SQL  &middot;  Bash  &middot;  C',
        '',
        '  <span class="secondary">Backend &amp; Infrastructure:</span>',
        '    FastAPI  &middot;  SQLAlchemy  &middot;  PySpark  &middot;  Docker',
        '    Redis  &middot;  AWS (RDS, App Runner, ECR)  &middot;  GitHub Actions',
        '',
        '  <span class="secondary">Data &amp; ML:</span>',
        '    DuckDB  &middot;  Parquet  &middot;  ETL pipelines',
        '    PyTorch  &middot;  pandas  &middot;  NumPy  &middot;  mass spec analysis',
        '',
        '  <span class="secondary">Tools:</span>',
        '    Git  &middot;  pytest  &middot;  Pydantic  &middot;  Anthropic Claude API',
    ],

    resume: [
        '<span class="heading">─── Resume ─────────────────────────────────</span>',
        '',
        '  <span class="secondary">Languages:</span>',
        '    Python, Java, SQL, Bash, C, Go',
        '',
        '  <span class="secondary">Frameworks &amp; Tools:</span>',
        '    FastAPI, SQLAlchemy, pytest, PySpark, PyTorch,',
        '    Docker, AWS, Redis, Git, Anthropic Claude API',
        '',
        '  <span class="secondary">Education:</span>',
        '    M.S. Computer Science',
        '    Northeastern University, San Jose <span class="dim">&middot; May 2026</span>',
        '',
        '    B.A. Molecular &amp; Cell Biology: Neurobiology',
        '    University of California, Berkeley <span class="dim">&middot; May 2021</span>',
        '',
        '  <span class="secondary">Publication:</span>',
        '    MSstats+ enhances differential analysis in',
        '    proteomic experiments <span class="dim">&middot; bioRxiv 2025</span>',
        '    <a class="output-link" href="https://doi.org/10.1101/2025.09.11.675573" target="_blank" rel="noopener">&rarr; doi:10.1101/2025.09.11.675573</a>',
    ],

    contact: [
        '<span class="heading">─── Contact ────────────────────────────────</span>',
        '',
        '  <span class="dim">email</span>     <a class="output-link" href="mailto:manuel.ramon.magana@gmail.com">manuel.ramon.magana@gmail.com</a>',
        '  <span class="dim">github</span>    <a class="output-link" href="https://github.com/magana272" target="_blank" rel="noopener">github.com/magana272</a>',
        '  <span class="dim">linkedin</span>  <a class="output-link" href="https://linkedin.com/in/manuel-magana-359290160/" target="_blank" rel="noopener">linkedin.com/in/manuel-magana</a>',
        '',
        '  <span class="secondary">Open to:</span>',
        '    Full-time engineering roles, contract work,',
        '    and interesting side projects.',
    ],
};
