stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir -p public
    - find . -mindepth 1 -maxdepth 1 ! -name public ! -name .git -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
